import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';

import * as api from './api';
import PostsState from './types/PostsState';

const initialState: PostsState = {
	posts: [],
};

export const loadPosts = createAsyncThunk(
	'posts/loadPosts', // action type - тип действтия

	() => api.getAll() // action payload - полезная нагрузка
	// - то что призходит с бэка
);

export const postsSlice = createSlice({
	name: 'posts',
	initialState,
	// редюсеры - это те функции,
	// где не требуется делать ассинхронные запросы на бэк - оставили пустыми
	reducers: {},
	// The `extraReducers` field lets the slice handle actions defined elsewhere,
	// including actions generated by createAsyncThunk or in other slices.
	// экстраредюсеры - работают с асинхронными запросами
	// - например запросы на бэк
	extraReducers: (builder) => {
		builder.addCase(loadPosts.fulfilled, (state, action) => {
			state.posts = action.payload.posts;
		});
	},
});

export default postsSlice.reducer;
